import express from 'express';
import { isAuth } from '../middlewares/isAuth.js';
import uploadFile from '../middlewares/multer.js';
import { commentOnPin, createPin, deleteComment, deletePin, getAllPins, getSinglePins, updatePin } from '../controllers/pinController.js';
const router = express.Router();
router.post("/new",isAuth,uploadFile,createPin);
router.get("/all",isAuth,getAllPins);
router.get("/:id",isAuth,getSinglePins);
router.delete("/:id",isAuth,deletePin);
router.put("/:id",isAuth,updatePin);
router.post("/comment/:id",isAuth,commentOnPin);
router.delete("/comment/:id",isAuth,deleteComment);
export default router;